name: Run Crawlers on Schedule

on:
  schedule:
    - cron: '0 17 * * *'  # 0h VN
    - cron: '0 23 * * *'  # 6h VN
    - cron: '0 5 * * *'   # 12h VN
    - cron: '0 11 * * *'  # 18h VN
    - cron: '0 15 * * *'  # 22h VN

jobs:
  run-crawlers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas google-api-python-client

    - name: Run crawl_non_trending.py
      run: python crawl_non_trending.py

    - name: Run crawl_trending.py
      run: python crawl_trending.py