name: Run Crawlers

on:
  workflow_dispatch:   # Cho phép chạy thủ công
  schedule:
    - cron: "0 0,6,12,18 * * *"   # chạy 0h, 6h, 12h, 18h UTC mỗi ngày

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install google-api-python-client pandas

      - name: Run crawlers
        run: |
          python crawl_trending.py
          python crawl_non_trending.py

      - name: Set timestamp
        id: vars
        run: echo "ts=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_OUTPUT

      - name: Upload CSV results
        uses: actions/upload-artifact@v3
        with:
          name: youtube-data-${{ steps.vars.outputs.ts }}
          path: |
            youtube_trending.csv
            youtube_non_trending.csv
